name: pokedex_flutter_riverpod
description: "Flutter App for Pokedex with Riverpod"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.0.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  sprintf: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
