name: pokedex_flutter_riverpod
description: "Flutter App for Pokedex with Riverpod"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  flutter_riverpod: ^2.5.3
  go_router: ^14.3.0
  riverpod_annotation: ^2.5.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  custom_lint: ^0.6.7
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
